//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostEli.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DostEliEntities : DbContext
    {
        public DostEliEntities()
            : base("name=DostEliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table_Answer> Table_Answer { get; set; }
        public virtual DbSet<Table_AnswerLine> Table_AnswerLine { get; set; }
        public virtual DbSet<Table_Manager> Table_Manager { get; set; }
        public virtual DbSet<Table_Match> Table_Match { get; set; }
        public virtual DbSet<Table_Product> Table_Product { get; set; }
        public virtual DbSet<Table_ProductType> Table_ProductType { get; set; }
        public virtual DbSet<Table_Question> Table_Question { get; set; }
        public virtual DbSet<Table_User> Table_User { get; set; }
        public virtual DbSet<Table_Volunteer> Table_Volunteer { get; set; }
    }
}
