//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostEli.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_Volunteer
    {
        public int Volunteer_Id { get; set; }
        public string V_FirstName { get; set; }
        public string V_LastName { get; set; }
        public string V_Adress { get; set; }
        public string V_Email { get; set; }
        
        [DisplayName("Kullanýcý Adýnýz")]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string V_UserName { get; set; }
        
        [DisplayName("Þifreniz")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string V_Password { get; set; }
        
    }
}
