//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostEli.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_User
    {
       public int User_Id { get; set; }
        [DisplayName("Adýnýz")]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string UserFirstName { get; set; }
        [DisplayName("Soyadýnýz")]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string UserLastName { get; set; }
        [DisplayName("Adresiniz")]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string Adress { get; set; }
        [DisplayName("E-Mail")]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string Email { get; set; }
        [DisplayName("Kullanýcý Adýnýz")]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string UserName { get; set; }
        [DisplayName("Þifreniz")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string Password { get; set; }
        [DisplayName("Þifrenizi Tekrar Giriniz")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string ConfirmPassword { get; set; }
    }
}
