//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostEli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Answer
    {
        public int A_Id { get; set; }
        public string Volunteer_Id { get; set; }
        public string V_FirstName { get; set; }
        public string V_LastName { get; set; }
        public string User_Id { get; set; }
        public string Score { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public string CreateBy { get; set; }
    }
}
