//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostEli.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_Manager
    {
        public int Manager_Id { get; set; }
        public string M_FirstName { get; set; }
        public string M_LastName { get; set; }
        public string M_Email { get; set; }
        [DisplayName("Kullanýcý Adýnýz")]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string M_UserName { get; set; }
        [DisplayName("Þifreniz")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz")]
        public string M_Password { get; set; }
    }
}
