//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostEli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Match
    {
        public string Users { get; set; }
        public string Volunteers { get; set; }
        public int MatchingId { get; set; }
    }
    public class MatchModel
    {
        public List<Table_Match> match { get; set; }
    }
}
