//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DostEli.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Table_Product
    {
        public int Product_Id { get; set; }
        public string ProductName { get; set; }
        public string Price { get; set; }
        public int Type_id { get; set; }

        public virtual Table_ProductType Table_ProductType { get; set; }
        public bool IsChecked { get; set; }
    }
    public class ProductModel
    {
        public List<Table_Product> Products { get; set; }
    }
}
